@startuml E-R図
title IT単語帳

entity "単語(ローカル)" as LocalWord {
  * 単語ID : int <<PK>>
  --
  * 単語識別ID : int
  * 単語名 : String
  * 解説 : String
  * タグ : String
  * カテゴリ : String
  * 読み : String
  * 単語作成日時 : datetime
  * 最終編集日時 : datetime
  * 最終同期日時 : datetime
  * アップロード可否 : boolean
  * 公開範囲 : int
}

entity "解答" as Answer {
  * 解答ID : int <<PK>>
  --
  * 単語ID : int <<FK>>
  * 見直し : int
  * 総問題数 : int
  * 解答時間 : int
}

LocalWord ||--o{ Answer : "1対多"

@enduml