@startuml ITwordbook

left to right direction
title IT単語帳

[*] --> ホーム画面 : start.pyでアプリ起動

ホーム画面 --> 単語一覧画面
ホーム画面 --> 出題形式選択画面

単語一覧画面 --> 単語詳細画面
単語一覧画面 --> 単語登録画面

単語登録画面 --> 単語一覧画面 : 登録完了

出題形式選択画面 --> 問題画面
問題画面 --> 結果画面

state ホーム画面 : HomeView
state 単語一覧画面 : wordlist
state 単語詳細画面 : Wordbook
state 単語登録画面 : wordEntry
state 出題形式選択画面 : Q_Select
state 問題画面 : Q_quiz
state 結果画面 : Result

@enduml