@startuml ITwordbook

left to right direction
title IT単語帳

[*] --> ホーム画面 : start.pyでアプリ起動

ホーム画面 --> チュートリアル画面
ホーム画面 --> 単語一覧画面
ホーム画面 --> 出題形式選択画面
ホーム画面 --> ログイン画面

単語一覧画面 --> 単語詳細画面
単語一覧画面 --> 単語登録画面

単語登録画面 --> 単語一覧画面 : 登録完了

出題形式選択画面 --> 問題画面
問題画面 --> 結果画面

ログイン画面 --> 新規登録画面
ログイン画面 --> ログイン完了画面 : ログイン成功
ログイン画面 --> パスワードリセット画面

ログイン完了画面 --> 単語アップロード画面
ログイン完了画面 --> 単語ダウンロード画面
ログイン完了画面 -->アカウント管理画面

新規登録画面 --> ログイン画面 : 登録完了

パスワードリセット画面 --> ログイン画面 : リセット完了

state ホーム画面 : HomeView.py
state 単語一覧画面 : wordlist_view.py
state 単語詳細画面 : WordbookView.py(仮)
state 単語登録画面 : wordEntryView.py
state チュートリアル画面 : 余裕あったら実装

@enduml